#!/usr/bin/env python


from argparse import ArgumentParser, FileType
import sys
from pprint import pprint
from pycimc import UcsServer
import json

p = ArgumentParser(prog = 'cimc',
                   description = 'Control a UCS CIMC interface',
                   )
p.add_argument('-i', '--ip-address', help = 'IPv4 address of the host', required=True)
p.add_argument('-u', '--username', help = 'username', required=True)
p.add_argument('-p', '--password', help = 'password', required=True)
# p.add_argument('-c', '--session-cookie', help = 'session cookie')
p.add_argument('--get-cimc-info', action='store_true')
p.add_argument('--get-boot-order', action='store_true')
p.add_argument('--get-chassis-info', action='store_true')
p.add_argument('--get-drive-inventory', action='store_true')
p.add_argument('--get-interface-inventory', action='store_true')
p.add_argument('--get-pci-inventory', action='store_true')
p.add_argument('--get-bios-settings', action='store_true')
p.add_argument('--get-users', action='store_true')

args = p.parse_args()
# print args

'''
    Typical 'set' commands that we need to implement:
        set_power_state(self, power_state, force=False):
        print_drive_inventory(self)
        set_bios_custom(self)
        set_sol_adminstate(self, state='enable', speed='115200', comport='com0')
'''

with UcsServer(args.ip_address, args.username, args.password) as server:
    args = p.parse_args()
    # print args
    if args.get_cimc_info:
        server.get_cimc_info()
        print json.dumps(server.inventory['cimc'], indent=2)
    if args.get_boot_order:
        server.get_boot_order()
        print json.dumps(server.inventory['boot_order'], indent=2)
    if args.get_chassis_info:
        server.get_chassis_info()
        print json.dumps(server.inventory['chassis'], indent=2)
    if args.get_drive_inventory:
        server.get_drive_inventory()
        print json.dumps(server.inventory['drives'], indent=2)
    if args.get_interface_inventory:
        server.get_interface_inventory()
        print json.dumps(server.inventory['adaptor'], indent=2)
    if args.get_users:
        server.get_users()
        print json.dumps(server.inventory['users'], indent=2)
    if args.get_pci_inventory:
        server.get_pci_inventory()
        print json.dumps(server.inventory['pci'], indent=2)
    if args.get_bios_settings:
        server.get_bios_settings()
        print json.dumps(server.inventory['bios'], indent=2)

