from collections import namedtuple

REQUEST_TIMEOUT = 10.0
USERNAME='admin'
PASSWORD='password'
SERVERS = [
    '192.168.200.100',
    '192.168.200.101',
    # '172.29.85.36',
    # '172.29.85.37',
    # '172.29.85.38',
    # '172.29.85.39',
    # '172.29.85.40',
    # '172.29.85.41',
    # '172.29.85.42',
    # '172.29.85.43',
    # '172.29.85.51',
    # '172.29.85.52',
    # '172.29.85.53',
    # '172.29.85.54',
    # '172.29.85.55',
    # '172.29.85.56',
]

MoSetting = namedtuple('biosSetting',['tag','rn','setting'])
CUSTOM_BIOS_SETTINGS = (
    MoSetting('biosVfDemandScrub',
              'Demand-Scrub-Param',
              'vpDemandScrub="disabled"'),
    MoSetting('biosVfIntelTurboBoostTech',
              'Intel-Turbo-Boost-Tech',
              'vpIntelTurboBoostTech="disabled"'),
    MoSetting('biosVfHardwarePrefetch',
              'Hardware-Prefetch',
              'vpHardwarePrefetch="disabled"'),
    MoSetting('biosVfAdjacentCacheLinePrefetch',
              'Adjacent-Cache-Line-Prefetch',
              'vpAdjacentCacheLinePrefetch="disabled"'),
    MoSetting('biosVfProcessorC1E',
              'Processor-C1E',
              'vpProcessorC1E="disabled"'),
    MoSetting('biosVfDCUPrefetch',
              'DCU-Prefetch',
              'vpStreamerPrefetch="disabled" vpIPPrefetch="disabled"'),
    MoSetting('biosVfCPUPowerManagement',
              'CPU-PowerManagement',
              'vpCPUPowerManagement="custom"'),
    MoSetting('biosVfCPUFrequencyFloor',
              'CPU-FreqFloor',
              'vpCPUFrequencyFloor="enabled"'),
    MoSetting('biosVfCPUEnergyPerformance',
              'CPU-EngPerfBias',
              'vpCPUEnergyPerformance="performance"'),
    MoSetting('biosVfIntelVTForDirectedIO',
              'Intel-VT-for-directed-IO',
              'vpIntelVTDATSSupport="enabled" vpIntelVTDCoherencySupport="enabled" vpIntelVTForDirectedIO="enabled"'),
    MoSetting('biosVfDRAMClockThrottling',
              'DRAM-Clock-Throttling',
              'vpDRAMClockThrottling="Performance"'),
    MoSetting('biosVfPatrolScrub',
              'Patrol-Scrub-Param',
              'vpPatrolScrub="disabled"'),
)
